# Site settings
title: Répertoire International des Sources Musciales
email: info@rism-ch.org
description: "The Swiss RISM records music manuscripts and printed musical sources in Swiss libraries and archives"
baseurl: ""
resources: "http://admin.rism-ch.org"
url: "http://www.rism-ch.org"

menu:
    - id: about_us
      submenu:
          - id: committee
          - id: contact
          - id: association
          - id: central_redaction
    - id: cataloging
    - id: projects
    - id: links
    - id: musicians
    
search_options:
    - ["search_title", "title"]
    - ["search_composer", "composer"]
search_url: "http://www.rism-ch.org/catalog/"

# Build settings
#markdown: kramdown
markdown: redcarpet
