# Site settings
title: Répertoire International des Sources Musicales
email: info@rism-ch.org
description: "The Swiss RISM records music manuscripts and printed musical sources in Swiss libraries and archives"
baseurl: ""
resources: "http://www.rism-ch.org"
url: "http://rism-ch.org"

top_menu:
    - id: simple_search
      url: "http://www.rism-ch.org/catalog/?locale=en"
      localize: true
    - id: advanced_search
      url: "http://www.rism-ch.org/advanced/?locale=en"
      localize: true
    - id: search_history
      url: "http://www.rism-ch.org/search_history/?locale=en"
      localize: true
    - id: contact
    - id: index

menu:
    - id: about-us
      submenu:
          - id: committee
          - id: contact
          - id: association
          - id: press
          - id: central-redaction
            url: "http://www.rism.info"
            blank: true
    - id: cataloging
      submenu:
          - id: cataloging/reichel
          - id: cataloging/snb
          - id: cataloging/zhb-lu
          - id: cataloging/frey-gryn
          - id: cataloging/repertorium
          - id: cataloging/bern-bb
          - id: past-cataloging-projects
    - id: infrastructure
      submenu:
          - id: infrastructure/digital-music-unica-in-switzerland
          - id: infrastructure/muscat
          - id: infrastructure/mei
          - id: infrastructure/communication
          - id: past-infrastructure-projects
    - id: links
      submenu:
          - id: links/org-international
          - id: links/org-ch
          - id: links/dictionaries
          - id: links/music-dictionaries
          - id: links/finding-aid
          - id: links/source-catalogues
          - id: links/digitisation
          - id: links/repertoire
          - id: links/editions
          - id: links/varia
    - id: finding-aid
      submenu:
          - id: links/ch-people-a-e
          - id: links/ch-institutions
    - id: publications
      submenu:
          - id: d-lib
          - id: inventories
            url: "http://inventories.rism-ch.org"
            blank: true
          - id: psmd
            url: "http://www.printed-sacred-music.org"
            blank: true
          - id: publication-list
    - id: cds
      submenu:
          - id: cd-cazzati
          - id: cd-swiss-monasteries
    - id: faq
    
search_options:
    - ["search_any_field", "any_field"]
    - ["search_title", "title"]
    - ["search_composer", "composer"]
    - ["search_library", "library_siglum"]
    - ["search_subject", "subject"]
search_url: "http://www.rism-ch.org/catalog/"
advanced_search_url: "http://www.rism-ch.org/advanced/"

# Build settings
#markdown: kramdown
markdown: redcarpet

gems:
  - jekyll-redirect-from
