# Site settings
title: Répertoire International des Sources Musicales
email: info@rism-ch.org
description: "The Swiss RISM records music manuscripts and printed musical sources in Swiss libraries and archives"
baseurl: ""
resources: "http://admin.rism-ch.org"
url: "http://www.rism-ch.org"

top_menu:
    - id: advanced_search
      url: "http://129.194.18.233/advanced/"
    - id: search_history
      url: "http://129.194.18.233/search_history"
    - id: help
    - id: contact
    - id: index

menu:
    - id: about_us
      submenu:
          - id: committee
          - id: contact
          - id: association
          - id: central_redaction
            url: "http://www.rism.info"
            blank: true
    - id: cataloging
      submenu:
          - id: cataloging/bern-bb
          - id: cataloging/frey-gryn
          - id: cataloging/snb
          - id: cataloging/fischingen
          - id: cataloging/munzingeriana
          - id: cataloging/zhb-lu
          - id: cataloging/sarnen
          - id: cataloging/repertorium
          - id: past-cataloging-projects
    - id: projects
      submenu:
          - id: projects/muscat
          - id: projects/mei
          - id: projects/kapellmeisterbuch
          - id: projects/psmd
          - id: projects/communication
          - id: projects/onstage-gc
          - id: past-projects
    - id: links
      submenu:
          - id: links/org_international
          - id: links/org_ch
          - id: links/dictionaries
          - id: links/music_dictionaries
          - id: links/finding_aid
          - id: links/source_catalogues
          - id: links/digitisation
          - id: links/repertoire
          - id: links/editions
          - id: links/varia
    - id: finding_aid
      submenu:
          - id: links/ch_people_a_e
          - id: links/ch_institutions
    - id: musicians
    
search_options:
    - ["search_any_field", "any_field"]
    - ["search_title", "title"]
    - ["search_composer", "composer"]
search_url: "http://129.194.18.233/catalog/"

# Build settings
#markdown: kramdown
markdown: redcarpet

gems:
  - jekyll-redirect-from
